# Global project parameters

REGION = "EM"
CARBON_SCOPE = "SCOPE_1"

# Project timeline
START_ESTIMATION_YEAR = 2013
END_REBALANCE_YEAR = 2024
BACKTEST_START_YEAR = 2014
BACKTEST_END_YEAR = 2025

# Estimation and filtering rules
ROLLING_WINDOW_MONTHS = 120
MIN_HISTORY_MONTHS = 36
STALE_RETURN_THRESHOLD = 0.50
LOW_PRICE_THRESHOLD = 0.5

# Portfolio assumptions
INITIAL_WEALTH = 1_000_000
CARBON_REDUCTION_TARGET = 0.50
NET_ZERO_REDUCTION = 0.10